# Generated by Django 3.2.4 on 2021-06-12 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confessions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confession',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='confessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
