# Generated by Django 3.2 on 2021-06-17 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confessions_api', '0002_alter_confession_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
